/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewMealPlanSummaryRouteImport } from './routes/view-meal-plan-summary'
import { Route as GeneratePlanRouteImport } from './routes/generate-plan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsAddPatientRouteImport } from './routes/patients/add-patient'

const ViewMealPlanSummaryRoute = ViewMealPlanSummaryRouteImport.update({
  id: '/view-meal-plan-summary',
  path: '/view-meal-plan-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratePlanRoute = GeneratePlanRouteImport.update({
  id: '/generate-plan',
  path: '/generate-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsAddPatientRoute = PatientsAddPatientRouteImport.update({
  id: '/patients/add-patient',
  path: '/patients/add-patient',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate-plan': typeof GeneratePlanRoute
  '/view-meal-plan-summary': typeof ViewMealPlanSummaryRoute
  '/patients/add-patient': typeof PatientsAddPatientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate-plan': typeof GeneratePlanRoute
  '/view-meal-plan-summary': typeof ViewMealPlanSummaryRoute
  '/patients/add-patient': typeof PatientsAddPatientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate-plan': typeof GeneratePlanRoute
  '/view-meal-plan-summary': typeof ViewMealPlanSummaryRoute
  '/patients/add-patient': typeof PatientsAddPatientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generate-plan'
    | '/view-meal-plan-summary'
    | '/patients/add-patient'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generate-plan'
    | '/view-meal-plan-summary'
    | '/patients/add-patient'
  id:
    | '__root__'
    | '/'
    | '/generate-plan'
    | '/view-meal-plan-summary'
    | '/patients/add-patient'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratePlanRoute: typeof GeneratePlanRoute
  ViewMealPlanSummaryRoute: typeof ViewMealPlanSummaryRoute
  PatientsAddPatientRoute: typeof PatientsAddPatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view-meal-plan-summary': {
      id: '/view-meal-plan-summary'
      path: '/view-meal-plan-summary'
      fullPath: '/view-meal-plan-summary'
      preLoaderRoute: typeof ViewMealPlanSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate-plan': {
      id: '/generate-plan'
      path: '/generate-plan'
      fullPath: '/generate-plan'
      preLoaderRoute: typeof GeneratePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/add-patient': {
      id: '/patients/add-patient'
      path: '/patients/add-patient'
      fullPath: '/patients/add-patient'
      preLoaderRoute: typeof PatientsAddPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratePlanRoute: GeneratePlanRoute,
  ViewMealPlanSummaryRoute: ViewMealPlanSummaryRoute,
  PatientsAddPatientRoute: PatientsAddPatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
